ESSENTIAL_COLUMNS = [
    "ID do pedido",
    "Status do pedido",
    "Status da Devolução / Reembolso",
    "Data de criação do pedido",
    "Nome do Produto",
    "Quantidade",
    "Returned quantity",
    "Valor Total",
    "Desconto do vendedor",
    "Cupom do vendedor",
    "Cupom Shopee",
    "Taxa de Envio Reversa",
    "Taxa de transação",
    "Taxa de comissão bruta",
    "Taxa de comissão líquida",
    "Taxa de serviço bruta",
    "Taxa de serviço líquida",
    "Cidade",
    "UF",
]

MONEY_COLUMNS = [
    "Preço original",
    "Preço acordado",
    "Subtotal do produto",
    "Desconto do vendedor",
    "Desconto do vendedor.1",
    "Incentivo Shopee para ação comercial",
    "Ajuste por participação em ação comercial",
    "Cupom do vendedor",
    "Coin Cashback Voucher Amount Sponsored by Seller",
    "Cupom Shopee",
    "Desconto Shopee da Leve Mais por Menos",
    "Desconto da Leve Mais por Menos do vendedor",
    "Compensar Moedas Shopee",
    "Total descontado Cartão de Crédito",
    "Valor Total",
    "Taxa de envio pagas pelo comprador",
    "Desconto de Frete Aproximado",
    "Taxa de Envio Reversa",
    "Taxa de transação",
    "Taxa de comissão bruta",
    "Taxa de comissão líquida",
    "Taxa de serviço bruta",
    "Taxa de serviço líquida",
    "Total global",
    "Valor estimado do frete",
]

DATE_COLUMNS = [
    "Data de criação do pedido",
    "Hora do pagamento do pedido",
    "Hora completa do pedido",
]
